# Generated by Django 4.1.7 on 2023-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_massges_pojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_added'],
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.TextField()),
                ('time_added', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Massges',
        ),
        migrations.DeleteModel(
            name='pojects',
        ),
    ]
