# Generated by Django 4.1.7 on 2023-04-15 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_feadback_mentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('-date_added',)},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='time_added',
        ),
        migrations.AddField(
            model_name='projects',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
